name: Duolingo README Stats - NO AUTH

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-noauth:
    name: Update readme with your duolingo stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          DUOLINGO_USER_ID: 730772122
          FILE_NAME: README-DEMO-NOAUTH.md
          SHOW_STREAK_TIMEZONE: true